server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /clinika/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /clinika/index.html;
    }

    location /clinika/api/ {
        proxy_pass http://clinika-backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
