"""etap6_financial_ledger

Revision ID: 6f5a6624fa87
Revises: f8fec11962e4
Create Date: 2026-04-12 10:15:44.435476

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6f5a6624fa87'
down_revision: Union[str, None] = 'f8fec11962e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'confirmed', 'cancelled', 'completed', 'no_show', name='appointmentstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index('ix_appointments_date', table_name='appointments')
    op.drop_index('ix_appointments_patient', table_name='appointments')
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_patient_phone'), 'appointments', ['patient_phone'], unique=False)
    op.drop_constraint('uq_tenant_branding', 'tenant_branding', type_='unique')
    op.create_index(op.f('ix_tenant_branding_tenant_id'), 'tenant_branding', ['tenant_id'], unique=True)
    op.alter_column('tenant_licenses', 'valid_from',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('tenant_licenses', 'valid_until',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.drop_constraint('uq_tenant_license', 'tenant_licenses', type_='unique')
    op.create_index(op.f('ix_tenant_licenses_tenant_id'), 'tenant_licenses', ['tenant_id'], unique=True)
    op.drop_constraint('uq_tenants_domain', 'tenants', type_='unique')
    op.drop_constraint('uq_tenants_slug', 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_domain'), 'tenants', ['domain'], unique=True)

    # Таблица финансового реестра (append-only)
    op.create_table('ledger_entries',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('tenants.id', ondelete='SET NULL'), nullable=True),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('amount', sa.Numeric(12, 2), nullable=False),
        sa.Column('operation_type', sa.String(50), nullable=False),
        sa.Column('reference_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('reference_type', sa.String(50), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_by_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')),
    )
    op.create_index('ix_ledger_entries_tenant_id', 'ledger_entries', ['tenant_id'])
    op.create_index('ix_ledger_entries_user_id', 'ledger_entries', ['user_id'])
    op.create_index('ix_ledger_entries_operation_type', 'ledger_entries', ['operation_type'])
    op.create_index('ix_ledger_entries_reference_id', 'ledger_entries', ['reference_id'])
    op.create_index('ix_ledger_entries_created_at', 'ledger_entries', ['created_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_domain'), table_name='tenants')
    op.create_unique_constraint('uq_tenants_slug', 'tenants', ['slug'])
    op.create_unique_constraint('uq_tenants_domain', 'tenants', ['domain'])
    op.drop_index(op.f('ix_tenant_licenses_tenant_id'), table_name='tenant_licenses')
    op.create_unique_constraint('uq_tenant_license', 'tenant_licenses', ['tenant_id'])
    op.alter_column('tenant_licenses', 'valid_until',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tenant_licenses', 'valid_from',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_tenant_branding_tenant_id'), table_name='tenant_branding')
    op.create_unique_constraint('uq_tenant_branding', 'tenant_branding', ['tenant_id'])
    op.drop_index(op.f('ix_appointments_patient_phone'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.create_index('ix_appointments_patient', 'appointments', ['patient_phone'], unique=False)
    op.create_index('ix_appointments_date', 'appointments', ['appointment_date'], unique=False)
    op.alter_column('appointments', 'status',
               existing_type=sa.Enum('pending', 'confirmed', 'cancelled', 'completed', 'no_show', name='appointmentstatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_table('ledger_entries')
    # ### end Alembic commands ###
