"""initial_schema

Revision ID: bdc4ea7233ff
Revises: 
Create Date: 2026-04-12 05:20:13.381879

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bdc4ea7233ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_mis_log_created")
    op.drop_index('ix_mis_log_event', table_name='mis_integration_log')
    op.drop_table('mis_integration_log')
    op.drop_index('bonuses_referral_type_idx', table_name='bonuses')
    op.create_index(op.f('ix_bonuses_referral_id'), 'bonuses', ['referral_id'], unique=False)
    op.drop_constraint('clinic_schedules_clinic_id_day_of_week_key', 'clinic_schedules', type_='unique')
    op.drop_constraint('clinic_schedules_clinic_id_fkey', 'clinic_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'clinic_schedules', 'clinics', ['clinic_id'], ['id'])
    op.alter_column('discounts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('discounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_discounts_active', table_name='discounts')
    op.drop_index('idx_discounts_applies_to', table_name='discounts')
    op.drop_constraint('discounts_clinic_id_fkey', 'discounts', type_='foreignkey')
    op.drop_constraint('discounts_created_by_id_fkey', 'discounts', type_='foreignkey')
    op.drop_constraint('discounts_service_id_fkey', 'discounts', type_='foreignkey')
    op.create_foreign_key(None, 'discounts', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'discounts', 'services', ['service_id'], ['id'])
    op.create_foreign_key(None, 'discounts', 'clinics', ['clinic_id'], ['id'])
    op.alter_column('invitations', 'max_uses',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('invitations', 'uses_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('invitations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_invitations_code', table_name='invitations')
    op.drop_constraint('invitations_code_key', 'invitations', type_='unique')
    op.create_index(op.f('ix_invitations_code'), 'invitations', ['code'], unique=True)
    op.drop_constraint('kpi_targets_admin_id_month_key', 'kpi_targets', type_='unique')
    op.create_index(op.f('ix_kpi_targets_admin_id'), 'kpi_targets', ['admin_id'], unique=False)
    op.create_unique_constraint('uq_kpi_admin_month', 'kpi_targets', ['admin_id', 'month'])
    op.drop_constraint('referral_comments_referral_id_fkey', 'referral_comments', type_='foreignkey')
    op.create_foreign_key(None, 'referral_comments', 'referrals', ['referral_id'], ['id'])
    op.drop_index('idx_services_mis_clinic', table_name='services')
    op.drop_index('services_clinic_id_idx', table_name='services')
    op.create_index(op.f('ix_services_clinic_id'), 'services', ['clinic_id'], unique=False)
    op.drop_constraint('services_clinic_id_fkey', 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'clinics', ['clinic_id'], ['id'])
    op.alter_column('system_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.alter_column('system_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_foreign_key('services_clinic_id_fkey', 'services', 'clinics', ['clinic_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_services_clinic_id'), table_name='services')
    op.create_index('services_clinic_id_idx', 'services', ['clinic_id'], unique=False)
    op.create_index('idx_services_mis_clinic', 'services', ['mis_id', 'clinic_id'], unique=False)
    op.drop_constraint(None, 'referral_comments', type_='foreignkey')
    op.create_foreign_key('referral_comments_referral_id_fkey', 'referral_comments', 'referrals', ['referral_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_kpi_admin_month', 'kpi_targets', type_='unique')
    op.drop_index(op.f('ix_kpi_targets_admin_id'), table_name='kpi_targets')
    op.create_unique_constraint('kpi_targets_admin_id_month_key', 'kpi_targets', ['admin_id', 'month'])
    op.drop_index(op.f('ix_invitations_code'), table_name='invitations')
    op.create_unique_constraint('invitations_code_key', 'invitations', ['code'])
    op.create_index('idx_invitations_code', 'invitations', ['code'], unique=False)
    op.alter_column('invitations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('invitations', 'uses_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('invitations', 'max_uses',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.drop_constraint(None, 'discounts', type_='foreignkey')
    op.drop_constraint(None, 'discounts', type_='foreignkey')
    op.drop_constraint(None, 'discounts', type_='foreignkey')
    op.create_foreign_key('discounts_service_id_fkey', 'discounts', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('discounts_created_by_id_fkey', 'discounts', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('discounts_clinic_id_fkey', 'discounts', 'clinics', ['clinic_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_discounts_applies_to', 'discounts', ['applies_to'], unique=False)
    op.create_index('idx_discounts_active', 'discounts', ['is_active'], unique=False)
    op.alter_column('discounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('discounts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'clinic_schedules', type_='foreignkey')
    op.create_foreign_key('clinic_schedules_clinic_id_fkey', 'clinic_schedules', 'clinics', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('clinic_schedules_clinic_id_day_of_week_key', 'clinic_schedules', ['clinic_id', 'day_of_week'])
    op.drop_index(op.f('ix_bonuses_referral_id'), table_name='bonuses')
    op.create_index('bonuses_referral_type_idx', 'bonuses', ['referral_id', 'bonus_type'], unique=True)
    op.create_table('mis_integration_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='mis_integration_log_pkey')
    )
    op.create_index('ix_mis_log_event', 'mis_integration_log', ['event_type'], unique=False)
    op.create_index('ix_mis_log_created', 'mis_integration_log', [sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###
